const STATUS_OK = 200;
const STATUS_CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const CONFLICT = 409;
const INVALID_DATA = 422;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  BAD_REQUEST,
  NOT_FOUND,
  CONFLICT,
  INVALID_DATA,
};
