const OK_STATUS = 200;
const CREATED_STATUS = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const CONFLICT = 409;
const UNPROCESSABLE_ENTITY_STATUS = 422;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  BAD_REQUEST,
  NOT_FOUND,
  CONFLICT,
  UNPROCESSABLE_ENTITY_STATUS,
};
